import { escapeHTML as e, filterTerms } from './core.js';
import { icon } from './icons.js';
export const episodeURL = (id, tab = 'read', term) => `#/episode/${id}${tab !== 'read' || term ? `?${new URLSearchParams({ ...(tab !== 'read' ? { tab } : {}), ...(term ? { term } : {}) })}` : ''}`;
const smallButton = (action, label, image, attrs = '') => `<button class="icon-button" data-action="${action}" aria-label="${e(label)}" title="${e(label)}" ${attrs}>${icon(image)}</button>`;
const jp = text => `<span lang="ja">${e(text)}</span>`;
const translated = text => `<p class="translation">${e(text)}</p>`;
const pair = (x, actions = '') => `<div class="example"><div class="example-top"><p class="japanese" lang="ja">${e(x.ja)}</p>${actions ? `<div class="example-actions">${actions}</div>` : ''}</div>${translated(x.zh)}</div>`;
function badge(t) { return `<span class="usage ${t.usage === '面试推荐' ? 'recommended' : ['语气注意', '理解即可'].includes(t.usage) ? 'caution' : ''}">${e(t.usage)}</span>`; }
function progress(c, terms) { const n = terms.filter(t => c.store.mastered.includes(t.id)).length; return { n, total: terms.length, percent: terms.length ? Math.round(n / terms.length * 100) : 0 }; }
export function shell(c) {
  const entry = c.registry.episodes.find(x => x.id === c.route.id);
  const current = c.route.view === 'episodes' ? '全剧课程' : c.route.view === 'saved' ? '我的收藏' : `第${entry.number}集`;
  const p = progress(c, c.allTerms);
  return `<div class="app-shell"><div class="nav-backdrop" data-action="close-nav"></div><aside id="sidebar" class="sidebar" aria-label="课程导航">
    <a class="brand" href="#/episodes"><span class="brand-mark">${icon('book')}</span><span><strong lang="ja">無能の鷹</strong><small>IT职场日语学习笔记</small></span></a>
    <nav class="main-nav" aria-label="主要导航"><a href="#/episodes" ${c.route.view === 'episodes' ? 'aria-current="page"' : ''}>${icon('grid')}全剧课程<span class="nav-count">${c.registry.episodes.length}</span></a><a href="#/saved" ${c.route.view === 'saved' ? 'aria-current="page"' : ''}>${icon('bookmark')}我的收藏<span class="nav-count" id="saved-count">${c.store.bookmarks.length}</span></a></nav>
    <div class="rail-label"><span>剧集目录</span><span>${c.lessons.size} / ${c.registry.episodes.length} 已整理</span></div>
    <nav class="episode-nav" aria-label="选择剧集">${c.registry.episodes.map(x => `<a class="episode-link ${x.status === 'planned' ? 'planned' : ''}" href="${episodeURL(x.id)}" ${c.route.view === 'episode' && c.route.id === x.id ? 'aria-current="page"' : ''}><span class="episode-number">${x.id}</span><span><strong>第${x.number}集${x.number === 8 ? ' · 最终集' : ''}</strong><small>${x.status === 'published' ? e(x.title) : '待整理'}</small></span>${x.status === 'published' ? '<span class="ready-dot" aria-label="可学习"></span>' : ''}</a>`).join('')}</nav>
    <div class="sidebar-bottom"><div class="progress-label"><span>我的学习进度</span><strong>${p.n}<span> / ${p.total}</span></strong></div><progress value="${p.n}" max="${p.total || 1}" aria-label="已掌握表达数"></progress><p>每学会一句，就离自然表达更近一点。</p><button class="text-button" data-action="settings">${icon('settings')}阅读与数据设置</button><small>记录保存在当前浏览器，不自动跨设备同步。</small></div>
  </aside><div class="workspace"><header class="topbar"><div class="breadcrumbs">${smallButton('menu', '打开课程目录', 'menu', 'id="menu-button" aria-expanded="false" aria-controls="sidebar"')}<a href="#/episodes">学习笔记</a>${icon('chevron')}<span>${current}</span></div><div class="topbar-actions"><button class="quiet-button" data-action="settings">${icon('settings')}<span>阅读设置</span></button>${smallButton('theme', c.store.theme === 'light' ? '切换深色模式' : '切换浅色模式', c.store.theme === 'light' ? 'moon' : 'sun')}</div></header><main id="main" tabindex="-1">${mainView(c)}</main><footer class="site-footer"><span lang="ja">ドラマから、仕事で使える日本語へ。</span><span>非官方学习笔记 · 不提供视频或完整字幕</span></footer></div></div>`;
}
export function mainView(c) {
  if (c.route.view === 'episodes') return catalogue(c);
  if (c.route.view === 'saved') return saved(c);
  const lesson = c.lessons.get(c.route.id);
  if (!lesson) return pending(c);
  const p = progress(c, lesson.terms);
  return `<div class="page-content"><section class="lesson-hero"><div><h1>${e(lesson.title)}</h1><p class="hero-japanese" lang="ja">${e(lesson.japaneseTitle)}</p><p class="hero-description">${e(lesson.description)}</p><div class="lesson-meta"><span>${icon('book')}${lesson.terms.length} 个实用表达</span><span>${icon('edit')}${lesson.highlights.length} 句面试重点</span><span>${icon('circle')}<span id="lesson-progress">已掌握 ${p.n} / ${p.total}</span></span></div></div><span class="hero-number" aria-hidden="true">${lesson.id}</span></section>
  <details class="source-note"><summary>${icon('info')}例句为学习用改写，非逐字台词<span>说明与来源</span>${icon('chevron')}</summary><div><p>${e(lesson.notice)}</p><p>${e(lesson.context)}</p>${lesson.sources.map(s => `<a href="${e(s.url)}" target="_blank" rel="noopener noreferrer">${e(s.label)}${icon('external')}</a><p class="source-purpose">${e(s.purpose)}</p>`).join('')}</div></details>
  <nav class="study-tabs" aria-label="学习方式">${[['read', '表达精读', lesson.terms.length], ['interview', '面试速记', lesson.highlights.length], ['review', '自测复习', '']].map(([tab, label, count]) => `<a href="${episodeURL(lesson.id, tab)}" ${c.route.tab === tab ? 'aria-current="page"' : ''}>${label}${count ? `<span>${count}</span>` : ''}</a>`).join('')}</nav>
  ${c.route.tab === 'interview' ? interview(c, lesson) : c.route.tab === 'review' ? review(c, lesson) : reading(c, lesson)}</div>`;
}
function toolbar(c, terms, savedOnly = false) {
  const categories = [...new Set(terms.map(t => t.category))];
  return `<div class="filter-panel"><div class="search-row"><label class="search-field">${icon('search')}<span class="sr-only">搜索表达</span><input id="term-search" type="search" placeholder="搜索表达、读音或中文释义…" value="${e(c.query)}" autocomplete="off"></label><label class="category-field"><span class="sr-only">按主题筛选</span><select id="category-filter"><option value="all">全部主题</option>${categories.map(x => `<option value="${e(x)}" ${c.category === x ? 'selected' : ''}>${e(x)}</option>`).join('')}</select></label></div><div class="filter-bottom"><div class="filter-chips" aria-label="表达筛选">${[['all', '全部表达'], ['interview', '面试推荐'], ['caution', '语气注意'], ['unmastered', '未掌握']].map(([filter, label]) => `<button data-action="filter" data-value="${filter}" class="chip ${c.filter === filter ? 'active' : ''}" aria-pressed="${c.filter === filter}">${label}</button>`).join('')}</div><button class="text-button expand-button" data-action="expand-all">${c.expandAll ? '收起全部' : '展开全部'}</button></div><div class="results-line" id="results-count" role="status" aria-live="polite">${resultCount(c, terms, savedOnly)}</div></div>`;
}
export function resultCount(c, terms) { return `显示 ${filterTerms(terms, c, c.store).length} / ${terms.length} 个表达`; }
function reading(c, lesson) {
  return `<div class="reading-layout"><section class="reading-column" aria-label="表达学习">${toolbar(c, lesson.terms)}<div id="term-list">${termList(c, lesson.terms)}</div><section class="takeaways"><h2>这一集，值得带走的要点</h2>${lesson.takeaways.map((x, i) => `<div><span>0${i + 1}</span><p><strong lang="ja">${e(x.ja)}</strong><span class="translation">${e(x.zh)}</span></p></div>`).join('')}<a class="primary-button" href="${episodeURL(lesson.id, 'interview')}">练习${lesson.highlights.length}句面试表达${icon('arrow')}</a></section></section><aside class="lesson-outline" aria-label="本集表达目录"><div class="outline-sticky"><h2>本集学习路线</h2><p>点击表达，定位到学习卡。</p><nav>${lesson.terms.map((t, i) => `<a data-action="jump" data-id="${t.id}" href="${episodeURL(lesson.id, 'read', t.id)}"><span>${String(i + 1).padStart(2, '0')}</span><span lang="ja">${e(t.term)}</span>${c.store.mastered.includes(t.id) ? icon('check') : ''}</a>`).join('')}</nav><div class="outline-tip">${icon('book')}<p>先理解语境，再换成自己的经历。<br>不必一次记住全部表达。</p></div></div></aside></div>`;
}
export function termList(c, terms) {
  const matches = filterTerms(terms, c, c.store);
  if (!matches.length) return `<div class="empty-state">${icon('search')}<h2>没有找到匹配的表达</h2><p>可以试试更短的日语词、读音或中文关键词。</p><button class="secondary-button" data-action="clear-filters">清除筛选</button></div>`;
  return matches.map(t => termCard(c, t)).join('');
}
function termCard(c, t) {
  const saved = c.store.bookmarks.includes(t.id), mastered = c.store.mastered.includes(t.id);
  return `<article class="term-card ${mastered ? 'is-mastered' : ''}" id="term-${t.id}"><div class="term-actions">${smallButton('bookmark', `${saved ? '取消收藏' : '收藏'}：${t.term}`, 'bookmark', `data-id="${t.id}" aria-pressed="${saved}"`)}${smallButton('master', `${mastered ? '取消掌握' : '标为已掌握'}：${t.term}`, 'circle', `data-id="${t.id}" aria-pressed="${mastered}"`)}</div><details class="term-details" data-term="${t.id}" ${c.expanded.has(t.id) ? 'open' : ''}><summary><div class="term-summary"><span class="term-index">${t.id.split('-')[1]}</span><div class="term-heading"><div class="term-title-row"><h2 lang="ja">${e(t.term)}</h2>${icon('chevron')}</div><p class="reading" lang="ja">${e(t.reading)}</p><p class="term-meaning translation">${e(t.meaning)}</p><div class="term-labels">${badge(t)}<span>${e(t.category)}</span>${c.route.view === 'saved' ? `<span>第${Number(t.id.split('-')[0])}集</span>` : ''}<span class="mastered-label" ${mastered ? '' : 'hidden'}>已掌握</span></div></div></div></summary><div class="term-body"><section><h3>理解这个表达</h3><p class="explanation">${e(t.explanation)}</p><div class="collocations">${t.collocations.map(x => `<span lang="ja">${e(x)}</span>`).join('')}</div></section><section><h3>IT职场用法 <span>学习例句</span></h3>${t.work.map((x, i) => pair(x, smallButton('speak', '朗读职场例句', 'volume', `data-id="${t.id}" data-kind="work" data-index="${i}"`))).join('')}</section><section class="interview-box"><div class="section-heading"><h3>面试这样说</h3>${smallButton('copy', '复制面试回答', 'copy', `data-id="${t.id}" data-kind="interview"`)}${smallButton('speak', '朗读面试回答', 'volume', `data-id="${t.id}" data-kind="interview"`)}</div><p class="question" lang="ja">Q. ${e(t.question)}</p>${pair(t.interview)}</section><aside class="usage-note"><strong>${icon('info')}使用提醒</strong><p>${e(t.tip)}</p></aside><details class="note-editor"><summary>${icon('edit')}写一句我的用法${c.store.notes[t.id] ? '<span>已保存</span>' : ''}</summary><label for="note-${t.id}">把这个表达，换成你真实经历中的一句话。</label><textarea id="note-${t.id}" data-note="${t.id}" maxlength="5000" placeholder="例如：APIの仕様について、実装前に…">${e(c.store.notes[t.id] || '')}</textarea><div><small>仅保存在当前浏览器。</small><button class="secondary-button" data-action="save-note" data-id="${t.id}">保存例句</button></div></details><div class="card-footer"><button class="text-button" data-action="copy" data-id="${t.id}" data-kind="card">${icon('copy')}复制学习卡</button><button class="text-button" data-action="share" data-id="${t.id}">${icon('external')}复制定位链接</button></div></div></details></article>`;
}
function interview(c, lesson) {
  return `<section class="interview-page"><div class="section-intro"><div><h2>把表达用进你的回答里</h2><p>先读日语，再联系自己的经历。这里是回答模板，不是你的个人经历陈述。</p></div><button class="secondary-button" data-action="toggle-answers" aria-pressed="${c.hideAnswers}">${c.hideAnswers ? '显示参考回答' : '隐藏回答，先自己说'}</button></div>${lesson.highlights.map((h, i) => `<article class="interview-card"><div class="interview-number">0${i + 1}</div><div><h3>${e(h.label)}</h3><p class="interview-question" lang="ja">${e(h.question)}</p><div class="answer" ${c.hideAnswers ? 'hidden' : ''}>${pair(h)}<div class="inline-actions"><button class="text-button" data-action="highlight-copy" data-index="${i}">${icon('copy')}复制日语</button><button class="text-button" data-action="highlight-speak" data-index="${i}">${icon('volume')}朗读</button></div></div>${c.hideAnswers ? '<p class="answer-placeholder">先组织自己的回答，再点击上方按钮查看参考。</p>' : ''}<p class="practice-prompt">${icon('edit')}${e(h.prompt)}</p><a class="text-link" href="${episodeURL(lesson.id, 'read', h.termId)}">回到表达详解${icon('arrow')}</a></div></article>`).join('')}<div class="practice-structure"><h3>用自己的经历扩展成完整回答</h3><div><span>遇到什么情况</span>${icon('arrow')}<span>采取什么行动</span>${icon('arrow')}<span>结果与反思</span></div><p>只保留你确实做过的事。不必为了听起来专业而加入未经证实的数字或职责。</p></div></section>`;
}
function review(c, lesson) {
  const item = c.review.queue[c.review.index];
  const term = lesson.terms.find(t => t.id === item);
  if (!term) return `<section class="review-section"><div class="review-complete">${icon('circle')}<h2>${c.review.queue.length ? '这一轮练习完成了' : '开始一轮表达自测'}</h2><p>${c.review.queue.length ? `本轮练习 ${c.review.queue.length} 个表达。熟悉的表达已加入「已掌握」。` : '先看中文回想日语，再翻面检查。自测不等于自动认定掌握。'}</p><button class="primary-button" data-action="restart-review">再练一轮${icon('refresh')}</button><a class="text-link" href="${episodeURL(lesson.id)}">返回表达精读</a></div></section>`;
  return `<section class="review-section"><div class="section-intro"><div><h2>先回想，再翻面</h2><p>看到中文意思，试着说出日语表达。</p></div><span class="review-count">${c.review.index + 1} / ${c.review.queue.length}</span></div><div class="review-card"><span class="review-category">${e(term.category)}</span><p class="review-prompt">${e(term.meaning)}</p>${c.review.flipped ? `<div class="review-answer"><h3 lang="ja">${e(term.term)}</h3><p class="reading" lang="ja">${e(term.reading)}</p>${pair(term.interview)}<button class="text-button" data-action="speak" data-id="${term.id}" data-kind="term">${icon('volume')}听日语读音</button></div>` : '<p class="review-hint">不用急着翻面，给自己一点回想的时间。</p>'}<button class="${c.review.flipped ? 'quiet-button' : 'primary-button'}" data-action="flip-review" aria-pressed="${c.review.flipped}">${c.review.flipped ? '收起答案' : '翻面看答案'}${icon('refresh')}</button></div><div class="review-rating"><button class="secondary-button" data-action="rate-review" data-rating="again" ${c.review.flipped ? '' : 'disabled'}>还要练习</button><button class="primary-button" data-action="rate-review" data-rating="known" ${c.review.flipped ? '' : 'disabled'}>${icon('check')}已经掌握</button></div><p class="review-disclaimer">自测中文提示始终显示，不受「显示中文译文」设置影响。<br>浏览器朗读使用设备语音，不是原剧音频。</p></section>`;
}
function catalogue(c) {
  return `<div class="page-content catalogue"><section class="catalogue-hero"><h1>跟着日剧，学会职场日语。</h1><p lang="ja">無能の鷹 · 学習ノート</p><p>从剧情中的沟通与协作出发，把听懂的表达变成工作中会说的话。</p><a class="primary-button" href="${episodeURL(c.registry.defaultEpisode)}">开始学习第${Number(c.registry.defaultEpisode)}集${icon('arrow')}</a></section><div class="section-intro"><h2>全剧课程</h2><span>${c.lessons.size} 集可学习 · 其余内容待整理</span></div><div class="episode-grid">${c.registry.episodes.map(x => { const lesson = c.lessons.get(x.id), p = progress(c, lesson?.terms || []); return `<a class="episode-tile ${lesson ? 'published' : ''}" href="${episodeURL(x.id)}"><div><span class="tile-number">${x.id}</span><span class="tile-status">${lesson ? '可学习' : '待整理'}</span></div><h3>第${x.number}集${x.number === 8 ? ' · 最终集' : ''}</h3><p>${lesson ? e(lesson.title) : '学习材料尚未发布'}</p>${lesson ? `<div class="tile-bottom"><span>${lesson.terms.length} 个表达 · 已掌握 ${p.n}</span>${icon('arrow')}</div>` : '<div class="tile-bottom"><span>内容整理后将在这里更新</span></div>'}</a>`; }).join('')}</div><div class="catalogue-note"><h2>一套适合反复使用的学习笔记</h2><p>表达精读：读音、中文释义、搭配与IT场景例句。面试速记：把表达放进回答。自测复习：回想并标记掌握程度。收藏和个人例句可在阅读设置中导出备份。</p><p>本网站不提供视频、原剧音轨或完整字幕。已整理的是学习用改写内容。</p><a class="text-link" href="${e(c.registry.source)}" target="_blank" rel="noopener noreferrer">电视朝日 · 剧集信息${icon('external')}</a></div></div>`;
}
function saved(c) {
  const terms = c.allTerms.filter(t => c.store.bookmarks.includes(t.id));
  return `<div class="page-content saved-page"><section class="simple-hero"><h1>我的收藏</h1><p>把想再用一次的表达留在这里。已收藏 ${terms.length} 个表达。</p></section>${terms.length ? `${toolbar(c, terms, true)}<div id="term-list">${termList(c, terms)}</div>` : `<div class="empty-state">${icon('bookmark')}<h2>给想记住的表达，留一个书签</h2><p>在学习卡右上角点击收藏，这些表达就会出现在这里。</p><a class="primary-button" href="${episodeURL(c.registry.defaultEpisode)}">去学习第${Number(c.registry.defaultEpisode)}集${icon('arrow')}</a></div>`}</div>`;
}
function pending(c) {
  const entry = c.registry.episodes.find(x => x.id === c.route.id);
  return `<div class="page-content"><section class="pending-page"><span class="pending-number">${entry.id}</span><h1>第${entry.number}集的学习内容尚未整理</h1><p>目前已有${c.lessons.size}集学习材料。这里先保留课程入口，暂不提供未经整理的表达或剧情分析。</p><a class="primary-button" href="${episodeURL(c.registry.defaultEpisode)}">先学习第${Number(c.registry.defaultEpisode)}集${icon('arrow')}</a><a class="text-link" href="#/episodes">查看全剧课程</a></section></div>`;
}
export function settingsDialog(c) {
  return `<dialog id="settings-dialog" aria-labelledby="settings-title"><div class="dialog-heading"><div><h2 id="settings-title">让阅读更适合你</h2><p>阅读偏好和学习记录保存在当前浏览器。</p></div>${smallButton('close-dialog', '关闭阅读设置', 'close')}</div><div class="setting-row"><div><strong>正文字号</strong><p>调整日语例句与说明文字</p></div><div class="font-control"><button data-action="font" data-delta="-1" aria-label="减小字号" ${c.store.fontSize <= 16 ? 'disabled' : ''}>A−</button><span id="font-value">${c.store.fontSize}px</span><button data-action="font" data-delta="1" aria-label="增大字号" ${c.store.fontSize >= 22 ? 'disabled' : ''}>A+</button></div></div><div class="setting-row"><div><strong>深色模式</strong><p>在浅色与深色阅读主题间切换</p></div><button class="switch" role="switch" aria-checked="${c.store.theme === 'dark'}" aria-label="深色模式" data-action="theme"><span></span></button></div>${[['chinese', '显示中文译文', '关闭后隐藏释义与例句译文，说明仍保留'], ['reading', '显示假名读音', '关闭后练习直接阅读日语表达']].map(([key, title, note]) => `<div class="setting-row"><div><strong>${title}</strong><p>${note}</p></div><button class="switch" role="switch" aria-checked="${c.store[key]}" aria-label="${title}" data-action="preference" data-key="${key}"><span></span></button></div>`).join('')}<div class="data-settings"><h3>学习记录备份</h3><p>包含收藏、掌握标记、个人例句与阅读设置。清除浏览器数据会丢失记录；换设备时可先导出再导入。</p><div><button class="secondary-button" data-action="export">${icon('download')}导出记录</button><button class="secondary-button" data-action="import">${icon('upload')}导入记录</button><input type="file" id="import-file" accept="application/json,.json" hidden></div><p class="import-note">导入会替换本地记录；确认前不会覆盖。只读取本站导出的JSON文件。</p></div><div class="dialog-footer"><span>朗读使用浏览器/系统日语语音，部分设备可能不可用。</span><button class="primary-button" data-action="close-dialog">完成</button></div></dialog>`;
}
